function iladata = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ILADATA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  ILADATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  iladata = importfile("/home/hossein/projects/ZCU208/matlab/iladata.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Mar-2022 21:45:24

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SampleInBuffer", "SampleInWindow", "TRIGGER", "design_1_irf_ssrf_data_system_ilainstprobe0_1150", "design_1_irf_ssrf_data_system_ilainstprobe1_1150", "design_1_irf_ssrf_data_system_ilainstprobe2_1150", "design_1_irf_ssrf_data_system_ilainstprobe3_1150", "design_1_irf_ssrf_data_system_ilainstprobe4_1150", "design_1_irf_ssrf_data_system_ilainstprobe5_1150", "design_1_irf_ssrf_data_system_ilainstprobe6_1150", "design_1_irf_ssrf_data_system_ilainstprobe7_1150", "design_1_irf_ssrf_data_system_ilainstprobe8_1150", "design_1_irf_ssrf_data_system_ilainstprobe9_1150", "design_1_irf_ssrf_data_system_ilainstprobe10_1150", "design_1_irf_ssrf_data_system_ilainstprobe11_1150", "design_1_irf_ssrf_data_system_ilainstprobe12_1150", "design_1_irf_ssrf_data_system_ilainstprobe13_1150", "design_1_irf_ssrf_data_system_ilainstprobe14_1150", "design_1_irf_ssrf_data_system_ilainstprobe15_1150"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
iladata = readtable(filename, opts);

end